from pathlib import Path


CORE_PATH = Path(__file__).with_name("vev_trader_core.py")

VARIANTS = {
    "vev_trader_zscore.py": [
        'class Trader(BaseVevTrader):',
        '    VARIANT_NAME = "zscore_core"',
        '    STRATEGY_MODE = "zscore"',
    ],
    "vev_trader_bs.py": [
        'class Trader(BaseVevTrader):',
        '    VARIANT_NAME = "black_scholes_single_vol"',
        '    STRATEGY_MODE = "black_scholes"',
        '    ENABLE_VERTICAL_ARB = True',
    ],
    "vev_trader_smile.py": [
        'class Trader(BaseVevTrader):',
        '    VARIANT_NAME = "smile_residual_live"',
        '    STRATEGY_MODE = "smile"',
        '    USE_NORMALIZED_RESIDUAL_SCORE = True',
        '    USE_COMPRESSION_TRIGGER = True',
        '    USE_DYNAMIC_STRIKE_ACTIVATION = True',
        '    DYNAMIC_ACTIVATION_VEGA_MIN = 2.5',
        '    DYNAMIC_REVERSION_MIN_OBS = 6',
        '    DYNAMIC_REVERSION_HIT_RATE_MIN = 0.5',
    ],
    "vev_trader_baseline.py": [
        'class Trader(BaseVevTrader):',
        '    VARIANT_NAME = "baseline"',
    ],
    "vev_trader_simple.py": [
        'class Trader(BaseVevTrader):',
        '    VARIANT_NAME = "simple_residual_pair_legacy"',
        '    USE_NORMALIZED_RESIDUAL_SCORE = False',
        '    USE_COMPRESSION_TRIGGER = False',
        '    USE_DYNAMIC_STRIKE_ACTIVATION = False',
        '    ENABLE_IV_PAIR_TRADES = True',
        '    ENABLE_VERTICAL_ARB = True',
        '    SIGNAL_VOUCHERS = BaseVevTrader.CORE_TRADE_VOUCHERS',
        '    EXPANSION_TRADE_VOUCHERS = ()',
        '    RESIDUAL_DELTA_ENTRY_Z = 0.9',
        '    LATE_SESSION_START = 900_000',
        '    FINAL_FLATTEN_START = 980_000',
        '',
        '    def _should_cross_touch(self, position: int, target: int) -> bool:',
        '        return False',
    ],
    "vev_trader_stage1.py": [
        'class Trader(BaseVevTrader):',
        '    VARIANT_NAME = "stage1_normalized_residual"',
        '    USE_NORMALIZED_RESIDUAL_SCORE = True',
    ],
    "vev_trader_stage12.py": [
        'class Trader(BaseVevTrader):',
        '    VARIANT_NAME = "stage12_compression_trigger"',
        '    USE_NORMALIZED_RESIDUAL_SCORE = True',
        '    USE_COMPRESSION_TRIGGER = True',
    ],
    "vev_trader.py": [
        'class Trader(BaseVevTrader):',
        '    VARIANT_NAME = "smile_residual_live"',
        '    STRATEGY_MODE = "smile"',
        '    USE_NORMALIZED_RESIDUAL_SCORE = True',
        '    USE_COMPRESSION_TRIGGER = True',
        '    USE_DYNAMIC_STRIKE_ACTIVATION = True',
        '    DYNAMIC_ACTIVATION_VEGA_MIN = 2.5',
        '    DYNAMIC_REVERSION_MIN_OBS = 6',
        '    DYNAMIC_REVERSION_HIT_RATE_MIN = 0.5',
    ],
}


def main() -> None:
    core_source = CORE_PATH.read_text()
    header = "# Generated by build_vev_variants.py. Do not edit directly.\n\n"

    for filename, trader_lines in VARIANTS.items():
        body = core_source.rstrip() + "\n\n\n" + "\n".join(trader_lines) + "\n"
        Path(__file__).with_name(filename).write_text(header + body)


if __name__ == "__main__":
    main()
